using System;
using System.Linq;
using System.Xml.Linq;
using Microsoft.Win32;


namespace ScannerClient_obalkyknih
{
    public class UpdateChecker
    {
        /// <summary>
        /// Path to downloaded update
        /// </summary>
        public string FilePath { get; private set; }
        
        /// <summary>
        /// Indicates whether current version is supported
        /// </summary>
        public bool IsSupportedVersion { get; private set; }
        
        /// <summary>
        /// Indicates whether newer version is available
        /// </summary>
        public bool IsUpdateAvailable { get; private set; }

        /// <summary>
        /// Gets latest available version number
        /// </summary>
        public Version AvailableVersion { get; private set; }

        /// <summary>
        /// Gets date of latest version
        /// </summary>
        public string AvailableVersionDate { get; private set; }

        /// <summary>
        /// Gets download link for latest available version
        /// </summary>
        public string DownloadLink { get; private set; }

        /// <summary>
        /// Gets checksum for latest available version setup file
        /// </summary>
        public string Checksum { get; private set; }

        /// <summary>
        /// Retrieves all possible information about updates and saves them to properties
        /// </summary>
        public void RetrieveUpdateInfo()
        {
            try
            {
                XDocument xDocument = XDocument.Load(Settings.UpdateServer.TrimEnd('/') + "/update-info.xml");

                //check if current version is in list of unsupported versions
                var unsupportedVersionElements = xDocument.Root.Element("unsupported-versions").Elements("version");
                int count = unsupportedVersionElements.Count(
                    el => (int.Parse(el.Element("major").Value) == Settings.Version.Major && int.Parse(el.Element("minor").Value) == Settings.Version.Minor)
                    );
                if (count == 0)
                {
                    this.IsSupportedVersion = true;
                }
                else
                {
                    this.IsSupportedVersion = false;
                }

                bool isAdminType = IsAdminInstallationType();
                //check if update is available
                var latestversionAvailableElements = xDocument.Root.Element("latest-version").Elements("version");
                foreach (var latestversionAvailable in latestversionAvailableElements)
                {
                    string type = latestversionAvailable.Attribute("type").Value;
                    if (isAdminType && !type.ToLower().Equals("admin"))
                    {
                        continue;
                    }
                    if (!isAdminType && type.ToLower().Equals("admin"))
                    {
                        continue;
                    }
                    int major = int.Parse(latestversionAvailable.Element("major").Value);
                    int minor = int.Parse(latestversionAvailable.Element("minor").Value);
                    this.AvailableVersion = new Version(major, minor);
                    this.DownloadLink = latestversionAvailable.Element("download").Value;
                    this.AvailableVersionDate = latestversionAvailable.Element("date").Value;
                    this.Checksum = latestversionAvailable.Element("checksum").Value;
                    this.FilePath = Settings.TemporaryFolder.TrimEnd('\\') + "\\" + this.DownloadLink.Substring(this.DownloadLink.LastIndexOf('/') + 1);
                }

                // if download link is still not set, it means that udate-info has wron format
                if (this.DownloadLink == null)
                {
                    throw new FormatException();
                }

                if (!this.IsSupportedVersion || Settings.Version.CompareTo(AvailableVersion) < 0)
                {
                    this.IsUpdateAvailable = true;
                }
            }
            catch (Exception ex)
            {
                if (ex is ArgumentNullException || ex is FormatException || ex is OverflowException)
                {
                    throw new FormatException("Wrong format of updateInfo on server.");
                }
                else
                {
                    throw;
                }
            }
        }

        // Looks into registry and finds out installation type
        private bool IsAdminInstallationType()
        {
            // Path to key generated by inno setup installer during installation process
            const string subkey = @"Software\Microsoft\Windows\CurrentVersion\Uninstall\ObalkyKnih-scanner_is1";

            // Try to open HKCU uninstall obalkyknih registry key
            RegistryKey regKey = Registry.CurrentUser.OpenSubKey(subkey);
            if (regKey != null)
            {
                return false;
            }
            return true;
        }

    }
}
