INSERT INTO eshop (id) VALUES (101);
UPDATE eshop SET id = '101' WHERE id = 101;
UPDATE eshop SET name = 'Kanzelsberger' WHERE id = 101;
UPDATE eshop SET try_count = '0' WHERE id = 101;
UPDATE eshop SET hit_count = '0' WHERE id = 101;
UPDATE eshop SET fullname = 'Kanzelsberger' WHERE id = 101;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 101;
UPDATE eshop SET web_url = 'http://www.kanzelsberger.cz' WHERE id = 101;
INSERT INTO eshop (id) VALUES (102);
UPDATE eshop SET id = '102' WHERE id = 102;
UPDATE eshop SET name = 'Martinus' WHERE id = 102;
UPDATE eshop SET try_count = '3903578' WHERE id = 102;
UPDATE eshop SET hit_count = '21713' WHERE id = 102;
UPDATE eshop SET fullname = 'Martinus' WHERE id = 102;
UPDATE eshop SET logo_url = '' WHERE id = 102;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 102;
UPDATE eshop SET web_url = 'http://www.martinus.sk' WHERE id = 102;
INSERT INTO eshop (id) VALUES (103);
UPDATE eshop SET id = '103' WHERE id = 103;
UPDATE eshop SET name = 'TOC' WHERE id = 103;
UPDATE eshop SET try_count = '0' WHERE id = 103;
UPDATE eshop SET hit_count = '0' WHERE id = 103;
UPDATE eshop SET fullname = 'NK Praha' WHERE id = 103;
UPDATE eshop SET logo_url = '' WHERE id = 103;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 103;
UPDATE eshop SET web_url = 'http://www.nkp.cz' WHERE id = 103;
INSERT INTO eshop (id) VALUES (104);
UPDATE eshop SET id = '104' WHERE id = 104;
UPDATE eshop SET name = 'Legacy' WHERE id = 104;
UPDATE eshop SET try_count = '0' WHERE id = 104;
UPDATE eshop SET hit_count = '0' WHERE id = 104;
UPDATE eshop SET fullname = 'Legacy' WHERE id = 104;
UPDATE eshop SET logo_url = '' WHERE id = 104;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 104;
UPDATE eshop SET web_url = 'http://www.obalkyknih.cz/#legacy' WHERE id = 104;
INSERT INTO eshop (id) VALUES (105);
UPDATE eshop SET id = '105' WHERE id = 105;
UPDATE eshop SET name = 'Static' WHERE id = 105;
UPDATE eshop SET try_count = '3882810' WHERE id = 105;
UPDATE eshop SET hit_count = '10' WHERE id = 105;
UPDATE eshop SET fullname = 'Static' WHERE id = 105;
UPDATE eshop SET logo_url = '' WHERE id = 105;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 105;
UPDATE eshop SET web_url = 'http://www.obalkyknih.cz/#static' WHERE id = 105;
INSERT INTO eshop (id) VALUES (106);
UPDATE eshop SET id = '106' WHERE id = 106;
UPDATE eshop SET name = 'SCKN' WHERE id = 106;
UPDATE eshop SET try_count = '0' WHERE id = 106;
UPDATE eshop SET hit_count = '0' WHERE id = 106;
UPDATE eshop SET fullname = 'Svaz českých nakladatelů a knihkupců' WHERE id = 106;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 106;
UPDATE eshop SET web_url = 'http://www.sckn.cz/ceskeknihy/' WHERE id = 106;
INSERT INTO eshop (id) VALUES (107);
UPDATE eshop SET id = '107' WHERE id = 107;
UPDATE eshop SET name = 'SKAT' WHERE id = 107;
UPDATE eshop SET try_count = '0' WHERE id = 107;
UPDATE eshop SET hit_count = '0' WHERE id = 107;
UPDATE eshop SET fullname = 'SKAT' WHERE id = 107;
UPDATE eshop SET logo_url = '' WHERE id = 107;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 107;
UPDATE eshop SET web_url = 'http://www.skat.cz' WHERE id = 107;
INSERT INTO eshop (id) VALUES (108);
UPDATE eshop SET id = '108' WHERE id = 108;
UPDATE eshop SET name = 'Amazon' WHERE id = 108;
UPDATE eshop SET try_count = '5545099' WHERE id = 108;
UPDATE eshop SET hit_count = '1640218' WHERE id = 108;
UPDATE eshop SET fullname = 'Amazon' WHERE id = 108;
UPDATE eshop SET logo_url = '' WHERE id = 108;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 108;
UPDATE eshop SET web_url = 'http://www.amazon.com' WHERE id = 108;
INSERT INTO eshop (id) VALUES (109);
UPDATE eshop SET id = '109' WHERE id = 109;
UPDATE eshop SET name = 'Upload' WHERE id = 109;
UPDATE eshop SET try_count = '0' WHERE id = 109;
UPDATE eshop SET hit_count = '0' WHERE id = 109;
UPDATE eshop SET fullname = 'Upload' WHERE id = 109;
UPDATE eshop SET logo_url = '' WHERE id = 109;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 109;
UPDATE eshop SET web_url = 'http://www.obalkyknih.cz/' WHERE id = 109;
INSERT INTO eshop (id) VALUES (110);
UPDATE eshop SET id = '110' WHERE id = 110;
UPDATE eshop SET name = 'OpenLibrary' WHERE id = 110;
UPDATE eshop SET try_count = '3902853' WHERE id = 110;
UPDATE eshop SET hit_count = '0' WHERE id = 110;
UPDATE eshop SET fullname = 'OpenLibrary' WHERE id = 110;
UPDATE eshop SET logo_url = '' WHERE id = 110;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 110;
UPDATE eshop SET web_url = 'http://www.openlibrary.org' WHERE id = 110;
INSERT INTO eshop (id) VALUES (111);
UPDATE eshop SET id = '111' WHERE id = 111;
UPDATE eshop SET name = '' WHERE id = 111;
UPDATE eshop SET try_count = '2113912' WHERE id = 111;
UPDATE eshop SET hit_count = '1612' WHERE id = 111;
UPDATE eshop SET fullname = 'Zboží.cz' WHERE id = 111;
UPDATE eshop SET logo_url = '' WHERE id = 111;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 111;
UPDATE eshop SET web_url = 'http://www.zbozi.cz' WHERE id = 111;
INSERT INTO eshop (id) VALUES (112);
UPDATE eshop SET id = '112' WHERE id = 112;
UPDATE eshop SET name = '' WHERE id = 112;
UPDATE eshop SET try_count = '0' WHERE id = 112;
UPDATE eshop SET hit_count = '0' WHERE id = 112;
UPDATE eshop SET fullname = 'Nakladatelství FRAGMENT, s.r.o.' WHERE id = 112;
UPDATE eshop SET xmlfeed_url = 'http://www.fragment.cz/xml/zbozi_hyperzbozi.xml' WHERE id = 112;
UPDATE eshop SET web_url = 'http://www.fragment.cz' WHERE id = 112;
INSERT INTO eshop (id) VALUES (113);
UPDATE eshop SET id = '113' WHERE id = 113;
UPDATE eshop SET name = '' WHERE id = 113;
UPDATE eshop SET try_count = '0' WHERE id = 113;
UPDATE eshop SET hit_count = '0' WHERE id = 113;
UPDATE eshop SET fullname = 'Městská knihovna v Praze' WHERE id = 113;
UPDATE eshop SET logo_url = '' WHERE id = 113;
UPDATE eshop SET xmlfeed_url = 'http://web2.mlp.cz/koweb/MKP_OBALKY_OBSAHY.XML' WHERE id = 113;
UPDATE eshop SET web_url = 'http://www.mlp.cz' WHERE id = 113;
INSERT INTO eshop (id) VALUES (114);
UPDATE eshop SET id = '114' WHERE id = 114;
UPDATE eshop SET name = '' WHERE id = 114;
UPDATE eshop SET try_count = '0' WHERE id = 114;
UPDATE eshop SET hit_count = '0' WHERE id = 114;
UPDATE eshop SET fullname = 'Knihy.ABZ.cz' WHERE id = 114;
UPDATE eshop SET logo_url = '' WHERE id = 114;
UPDATE eshop SET xmlfeed_url = 'http://knihy.abz.cz/feeds/jyxofeed.xml' WHERE id = 114;
UPDATE eshop SET web_url = 'http://www.abz.cz' WHERE id = 114;
INSERT INTO eshop (id) VALUES (115);
UPDATE eshop SET id = '115' WHERE id = 115;
UPDATE eshop SET name = '' WHERE id = 115;
UPDATE eshop SET try_count = '0' WHERE id = 115;
UPDATE eshop SET hit_count = '0' WHERE id = 115;
UPDATE eshop SET fullname = 'Cpress' WHERE id = 115;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 115;
UPDATE eshop SET web_url = 'http://knihy.cpress.cz' WHERE id = 115;
INSERT INTO eshop (id) VALUES (116);
UPDATE eshop SET id = '116' WHERE id = 116;
UPDATE eshop SET name = '' WHERE id = 116;
UPDATE eshop SET try_count = '0' WHERE id = 116;
UPDATE eshop SET hit_count = '0' WHERE id = 116;
UPDATE eshop SET fullname = 'Euromedia, a.s.' WHERE id = 116;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 116;
UPDATE eshop SET web_url = 'http://www.knizniweb.cz/jnp/cz/index.html' WHERE id = 116;
INSERT INTO eshop (id) VALUES (117);
UPDATE eshop SET id = '117' WHERE id = 117;
UPDATE eshop SET name = '' WHERE id = 117;
UPDATE eshop SET try_count = '0' WHERE id = 117;
UPDATE eshop SET hit_count = '0' WHERE id = 117;
UPDATE eshop SET fullname = 'Kosmas' WHERE id = 117;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 117;
UPDATE eshop SET web_url = 'http://www.kosmas.cz' WHERE id = 117;
INSERT INTO eshop (id) VALUES (118);
UPDATE eshop SET id = '118' WHERE id = 118;
UPDATE eshop SET name = '' WHERE id = 118;
UPDATE eshop SET try_count = '0' WHERE id = 118;
UPDATE eshop SET hit_count = '0' WHERE id = 118;
UPDATE eshop SET fullname = 'Librex' WHERE id = 118;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 118;
UPDATE eshop SET web_url = 'http://www.librex.cz' WHERE id = 118;
INSERT INTO eshop (id) VALUES (119);
UPDATE eshop SET id = '119' WHERE id = 119;
UPDATE eshop SET name = '' WHERE id = 119;
UPDATE eshop SET try_count = '0' WHERE id = 119;
UPDATE eshop SET hit_count = '0' WHERE id = 119;
UPDATE eshop SET fullname = 'Vltava, a.s.' WHERE id = 119;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 119;
UPDATE eshop SET web_url = 'http://www.vltavastores.cz/' WHERE id = 119;
INSERT INTO eshop (id) VALUES (120);
UPDATE eshop SET id = '120' WHERE id = 120;
UPDATE eshop SET name = '' WHERE id = 120;
UPDATE eshop SET try_count = '0' WHERE id = 120;
UPDATE eshop SET hit_count = '0' WHERE id = 120;
UPDATE eshop SET fullname = 'Pavel Dobrovský' WHERE id = 120;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 120;
UPDATE eshop SET web_url = 'http://www.dobrovsky.cz' WHERE id = 120;
INSERT INTO eshop (id) VALUES (121);
UPDATE eshop SET id = '121' WHERE id = 121;
UPDATE eshop SET name = '' WHERE id = 121;
UPDATE eshop SET try_count = '0' WHERE id = 121;
UPDATE eshop SET hit_count = '0' WHERE id = 121;
UPDATE eshop SET fullname = 'Knizní velkoobchod Pemic, a.s' WHERE id = 121;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 121;
UPDATE eshop SET web_url = 'http://www.pemic.cz' WHERE id = 121;
INSERT INTO eshop (id) VALUES (122);
UPDATE eshop SET id = '122' WHERE id = 122;
UPDATE eshop SET name = '' WHERE id = 122;
UPDATE eshop SET try_count = '0' WHERE id = 122;
UPDATE eshop SET hit_count = '0' WHERE id = 122;
UPDATE eshop SET fullname = 'Svět dětské fantazie' WHERE id = 122;
UPDATE eshop SET xmlfeed_url = '' WHERE id = 122;
UPDATE eshop SET web_url = 'http://www.svetdetskefantazie.cz/' WHERE id = 122;

UPDATE eshop SET logo_url = '/img/loga/loga_beta.png' WHERE id = 120;
UPDATE eshop SET logo_url = '/img/loga/loga_cpress.png' WHERE id = 115;
UPDATE eshop SET logo_url = '/img/loga/loga_dum.png' WHERE id = 122;
UPDATE eshop SET logo_url = '/img/loga/loga_kanzelsberger.png' WHERE id = 101;
UPDATE eshop SET logo_url = '/img/loga/loga_knizniweb.png' WHERE id = 116;
UPDATE eshop SET logo_url = '/img/loga/loga_kosmas.png' WHERE id = 117;
UPDATE eshop SET logo_url = '/img/loga/loga_librex.png' WHERE id = 118;
UPDATE eshop SET logo_url = '/img/loga/loga_pemic.png' WHERE id = 121;
UPDATE eshop SET logo_url = '/img/loga/loga_scks.png' WHERE id = 106;
UPDATE eshop SET logo_url = '/img/loga/loga_vltavastores.png' WHERE id = 119;

