---
abstract: 'Catalyst based application'
author:
  - ',,,'
build_requires:
  ExtUtils::MakeMaker: '6.36'
configure_requires:
  ExtUtils::MakeMaker: '6.36'
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Obalky
no_index:
  directory:
    - inc
    - t
requires:
  Business::ISBN: 0
  Cache::FastMmap: 0
  Catalyst: '5.7003'
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::View::TT: 0
  DBD::mysql: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::TimeStamp: 0
  Data::Structure::Util: 0
  Date::Simple: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::MySQL: 0
  Digest::SHA1: 0
  FCGI: 0
  HTML::Tiny: 0
  HTML::TreeBuilder::XPath: 0
  IO::Scalar: 0
  List::MoreUtils: 0
  MD5: 0
  Net::OAI::Harvester: 0
  Template: 0
  Template::Timer: 0
  Test::Pod::Coverage: 0
  Text::CSV::Encoded: 0
  XML::LibXML: 0
  XML::Simple: 0
  YAML: 0
  ZOOM: 0
resources:
  license: http://dev.perl.org/licenses/
version: '2.00'
