<div class="row">
    <div class="col-xs-12">

<?php

// echo "<h2>Debug $debug</h2>";
echo "<h1>Seznam úloh</h1>";
?>
<a class="add float-right" href="#"><span class="fas fa-plus-square"></span></a>
<?php
if ($tasks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Kód úlohy</th>
            <th>Popis</th>
            <th>Posledný stav</th>
            <th>Nasledujíci spuštení</th>
            <th>Akce</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Počet záznamů: <?php echo $tasks->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($tasks as $task) { ?>
            <tr>
                <td><?php echo $task->task_code; ?></td>
                <td><?php echo $task->description; ?></td>
                <?php
                if ($last_run[$task->task_code] == 'FAILED') {
                  echo "<td class='bg-danger text-white'>", $last_run[$task->task_code], "</td>";
                }
                else {
                  echo "<td>", $last_run[$task->task_code], "</td>";
                }
                ?>
                <td><?php echo $next_run[$task->task_code]; ?></td>
                <td><a class="edit" href="#"><span class="fas fa-edit"></span></a>
                <a class="delete" href="#"><span class="fas fa-times"></span></a>
                <a class="view_logs" href="<?php echo $this->url->get('logs') , '?task_code=', $task->task_code;?>"><span class="fas fa-arrow-right"></span></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

?>

<div id="modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Editace úlohy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="save_button">Uložit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
      </div>
    </div>
  </div>
</div>

<div id="modal_add" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Vytvorenie úlohy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="add_button">Uložit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
      </div>
    </div>
  </div>
</div>

<div id="modal_delete" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Vymazání úlohy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Chete vymazat úlohu <b><i class="title"></i></b> ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-ok" id="delete_button" data-dismiss="modal">Vymazat</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
      </div>
    </div>
  </div>
</div>

</div>
</div>
