<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OKCZ dohled</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/main.css">
    <script src="https://kit.fontawesome.com/2a37943f1d.js" crossorigin="anonymous"></script>
    <script src="js/jquery-3.4.1.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="js/main.js" type="text/javascript"></script>
</head>
<body>
    <div class="navbar navbar-light fixed-top navbar-expand-md">
        <div class="container">
            <a class="navbar-brand" href="<?php echo  $this->url->getBaseUri();?>">
                <i class="fas fa-cog"></i>OKCZ dohled
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item menu-biblio active"><a class="nav-link" href="<?php echo $this->url->getBaseUri();?>">Úlohy</a></li>
                    <li class="nav-item menu-archive"><a class="nav-link" href="<?php echo $this->url->get('logs'); ?>">Log</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>
</body>
</html>
